version: '3.8'

services:
  nginx:
    image: openresty/openresty:latest  # Используем образ с поддержкой Lua
    container_name: api-gateway
    ports:
      - "80:80"
      # - "443:443"            # раскомментить при HTTPS
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      # статика фронтенда
      - ./frontend/dist:/usr/share/nginx/html:ro
      # - ./certs:/etc/nginx/certs:ro  #  если используете SSL
    networks:
      - appnet

  authentication-service:
    build: ./authentication-service
    container_name: authentication-service
    env_file:
      - authentication-service/.env
    ports:
      - "8083:8083"
    networks:
      - appnet
    depends_on:
      - mysql

  chat-service:
    build: ./chat-service
    container_name: chat-service
    env_file:
      - chat-service/.env
    ports:
      - "8082:8082"
    networks:
      - appnet
    depends_on:
      - mysql

  matchmaking-service:
    build: ./matchmaking-service
    container_name: matchmaking-service
    env_file:
      - matchmaking-service/.env
    ports:
      - "8081:8081"
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chat-service
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat-service
      MYSQL_PASSWORD: chat-service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - appnet

volumes:
  mysql_data:

networks:
  appnet:
    driver: bridge
