services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chat-service
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat-service
      MYSQL_PASSWORD: chat-service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
